"""Shared typed models for CastleRAG pipeline records and outputs."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Vocabulary types
# ---------------------------------------------------------------------------

SourceType = Literal[
    "main_clip",
    "main_event_summary",
    "transcript_window",
    "aux_heartrate",
    "aux_gaze",
    "aux_photo",
    "aux_thermal",
    "aux_video",
]

AuxSourceType = Literal[
    "aux_heartrate",
    "aux_gaze",
    "aux_photo",
    "aux_thermal",
    "aux_video",
]

Modality = Literal["video", "image", "text", "audio"]
CameraType = Literal["ego", "fixed"]
QuestionRoute = Literal["static_visual", "speech_text", "temporal", "mixed"]
AnswerChoice = Literal["a", "b", "c", "d"]


# ---------------------------------------------------------------------------
# Dataset records
# ---------------------------------------------------------------------------


class TranscriptSegment(BaseModel):
    """Raw ASR segment inside a transcript window."""

    start: float  # seconds, relative to hour
    end: float
    text: str


class TranscriptWindow(BaseModel):
    """Normalized transcript utterance window (≤15 s, ≤96 tokens).

    Used as the input unit for both BM25 lexical retrieval and OmniEmbed
    dense retrieval.  absolute_start/absolute_end are UTC Unix milliseconds.
    """

    transcript_window_id: str
    day: str
    camera_id: str
    camera_type: CameraType
    participant_id: Optional[str]
    room: Optional[str]
    hour: int
    transcript_text: str
    transcript_segments: List[TranscriptSegment] = Field(default_factory=list)
    speaker_hint: Optional[str] = None
    has_speech: bool = True
    transcript_char_len: int = 0
    absolute_start: int  # ms UTC
    absolute_end: int  # ms UTC
    version: str = "0.1.0"

    @field_validator("absolute_end")
    @classmethod
    def _end_after_start(cls, v: int, info: Any) -> int:
        start = (info.data or {}).get("absolute_start")
        if start is not None and v <= start:
            raise ValueError("absolute_end must be > absolute_start")
        return v


class ClipRecord(BaseModel):
    """Main 30-second ego-camera clip evidence record.

    Produced by the preprocessing pipeline and stored as JSONL in
    data/derived/chunks/.  source_video_path points to the hour MP4;
    retrieval_clip_path points to the 30-second subclip.
    """

    clip_id: str
    parent_source_id: str
    source_type: Literal["main_clip"] = "main_clip"
    modality: Literal["video"] = "video"
    day: str
    hour: int
    camera_id: str
    camera_type: CameraType
    participant_id: Optional[str] = None
    room: Optional[str] = None
    start_seconds: float
    end_seconds: float
    absolute_start: int  # ms UTC
    absolute_end: int  # ms UTC
    source_video_path: str
    retrieval_clip_path: Optional[str] = None
    sampled_frame_paths: List[str] = Field(default_factory=list)
    transcript_text: Optional[str] = None
    ocr_text: Optional[str] = None
    clip_caption: Optional[str] = None
    event_summary_id: Optional[str] = None
    has_speech: bool = False
    is_placeholder: bool = False
    linked_aux_ids: List[str] = Field(default_factory=list)
    version: str = "0.1.0"

    @field_validator("absolute_end")
    @classmethod
    def _end_after_start(cls, v: int, info: Any) -> int:
        start = (info.data or {}).get("absolute_start")
        if start is not None and v <= start:
            raise ValueError("absolute_end must be > absolute_start")
        return v


class EventSummaryRecord(BaseModel):
    """2-minute event summary covering 4 adjacent 30-second clips.

    Generated by the offline event-compression step (preprocess/event_compress.py).
    This is the primary text artifact for dense retrieval over long videos.
    """

    event_summary_id: str
    source_type: Literal["main_event_summary"] = "main_event_summary"
    day: str
    camera_id: str
    camera_type: CameraType
    participant_id: Optional[str] = None
    room: Optional[str] = None
    absolute_start: int  # ms UTC
    absolute_end: int  # ms UTC
    member_clip_ids: List[str] = Field(default_factory=list)
    member_transcript_window_ids: List[str] = Field(default_factory=list)
    event_summary: Optional[str] = None
    aggregated_ocr_text: Optional[str] = None
    linked_aux_ids: List[str] = Field(default_factory=list)
    version: str = "0.1.0"

    @field_validator("absolute_end")
    @classmethod
    def _end_after_start(cls, v: int, info: Any) -> int:
        start = (info.data or {}).get("absolute_start")
        if start is not None and v <= start:
            raise ValueError("absolute_end must be > absolute_start")
        return v


class AuxRecord(BaseModel):
    """Auxiliary modality record (heartrate, gaze, photo, thermal, auxiliary video)."""

    clip_id: str  # used as record id; named clip_id for schema compatibility
    source_type: AuxSourceType
    modality: Modality
    day: str
    camera_id: Optional[str] = None
    camera_type: Optional[CameraType] = None
    participant_id: Optional[str] = None
    room: Optional[str] = None
    absolute_start: int  # ms UTC
    absolute_end: int  # ms UTC
    aux_owner: Optional[str] = None
    asset_path: Optional[str] = None
    summary_text: Optional[str] = None
    raw_features: Optional[Dict[str, Any]] = None
    linked_main_clip_ids: List[str] = Field(default_factory=list)
    linked_event_summary_ids: List[str] = Field(default_factory=list)
    version: str = "0.1.0"

    @field_validator("absolute_end")
    @classmethod
    def _end_after_start(cls, v: int, info: Any) -> int:
        start = (info.data or {}).get("absolute_start")
        if start is not None and v <= start:
            raise ValueError("absolute_end must be > absolute_start")
        return v


# ---------------------------------------------------------------------------
# Qdrant point payload
# ---------------------------------------------------------------------------


class QdrantPoint(BaseModel):
    """Full Qdrant payload stored with every evidence point."""

    point_id: str
    record_id: str
    parent_source_id: Optional[str] = None
    source_type: str
    modality: str
    day: Optional[str] = None
    hour: Optional[int] = None
    camera_id: Optional[str] = None
    camera_type: Optional[str] = None
    participant_id: Optional[str] = None
    room: Optional[str] = None
    start_seconds: Optional[float] = None
    end_seconds: Optional[float] = None
    absolute_start: Optional[int] = None  # ms UTC integer (indexed)
    absolute_end: Optional[int] = None  # ms UTC integer (indexed)
    duration_seconds: Optional[float] = None
    transcript_text: Optional[str] = None
    event_summary: Optional[str] = None
    clip_caption: Optional[str] = None
    ocr_text: Optional[str] = None
    asset_path: Optional[str] = None
    sampled_frame_paths: List[str] = Field(default_factory=list)
    has_speech: bool = False
    is_placeholder: bool = False
    linked_aux_ids: List[str] = Field(default_factory=list)
    model_name: Optional[str] = None
    model_revision: Optional[str] = None
    build_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Retrieval and reranking
# ---------------------------------------------------------------------------


class RetrievalHit(BaseModel):
    """Single hit from retrieval (Qdrant dense or BM25 lexical)."""

    rank: int
    score: float
    point_id: str
    record_id: str
    source_type: str
    modality: str
    day: Optional[str] = None
    camera_id: Optional[str] = None
    participant_id: Optional[str] = None
    absolute_start: Optional[int] = None
    absolute_end: Optional[int] = None
    transcript_text: Optional[str] = None
    event_summary: Optional[str] = None
    ocr_text: Optional[str] = None
    asset_path: Optional[str] = None


class EvidencePack(BaseModel):
    """Route-aware reranker candidate assembled from retrieval hits."""

    pack_id: str
    route: QuestionRoute
    primary_hit: RetrievalHit
    retrieval_score: float = 0.0
    evidence_rows: List[RetrievalHit] = Field(default_factory=list)
    transcript_evidence: List[str] = Field(default_factory=list)
    event_summaries: List[str] = Field(default_factory=list)
    ocr_spans: List[str] = Field(default_factory=list)
    frame_descriptions: List[str] = Field(default_factory=list)
    auxiliary_notes: List[str] = Field(default_factory=list)


class RerankerOutput(BaseModel):
    """Structured JSON output from the reranker LLM per candidate pack."""

    relevance: int = Field(ge=0, le=4)
    support: Dict[str, int] = Field(description="Per-choice support scores 0-4")
    keep: bool
    rationale: str
    final_rerank_score: float = 0.0

    @field_validator("support")
    @classmethod
    def _validate_support(cls, v: Dict[str, int]) -> Dict[str, int]:
        for key in ("a", "b", "c", "d"):
            if key not in v:
                raise ValueError(f"support must contain key '{key}'")
            if not 0 <= v[key] <= 4:
                raise ValueError(f"support['{key}'] must be 0-4, got {v[key]}")
        return v


class RerankedEvidencePack(BaseModel):
    """Candidate pack plus reranker output and final score."""

    pack: EvidencePack
    reranker_output: RerankerOutput
    final_rerank_score: float


class RerankResult(BaseModel):
    """Top reranked packs, support priors, and flattened evidence rows."""

    route: QuestionRoute
    kept_packs: List[RerankedEvidencePack] = Field(default_factory=list)
    support_priors: Dict[str, float] = Field(
        default_factory=lambda: {"a": 0.0, "b": 0.0, "c": 0.0, "d": 0.0}
    )
    evidence_rows: List[RetrievalHit] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------


class EvalQuestion(BaseModel):
    """Official CASTLE question record."""

    question_id: str
    query: str
    answers: Dict[str, str] = Field(
        description="{'a': ..., 'b': ..., 'c': ..., 'd': ...}"
    )
    ground_truth: Optional[AnswerChoice] = None

    @field_validator("answers")
    @classmethod
    def _validate_answers(cls, v: Dict[str, str]) -> Dict[str, str]:
        for key in ("a", "b", "c", "d"):
            if key not in v:
                raise ValueError(f"answers must contain key '{key}'")
        return v


class Prediction(BaseModel):
    """Per-question prediction with optional evidence trace."""

    question_id: str
    predicted_answer: AnswerChoice
    route: Optional[QuestionRoute] = None
    support_priors: Optional[Dict[str, float]] = None
    top_evidence_ids: List[str] = Field(default_factory=list)
    raw_answer_text: Optional[str] = None
    confidence: Optional[float] = None
